[application]
name = "makego"
version = "0.1.0"
url = "https://github.com/DanielNos/MakeGo"
license = "OSL-3.0"
description = "A Go build and packaging tool."
long_description = "A Go build and packaging tool."

[build]
target = "."
flags = "-ldflags=\"-w -s\""
platforms = [ "linux/amd64" ]

[maintainer]
name = "Daniel Nos"
email = "nos.daniel@pm.me"

[package]
deb = true
rpm = true
