[application]
name = "makego"
version = "0.1.0"
url = "https://github.com/DanielNos/MakeGo"
license = "OSL-3.0"
description = "A Go build and packaging tool."
long_description = "A Go build and packaging tool."
gui = false

[desktop_entry]
name = "MakeGo"
icon = ""
categories = [ "Utility" ]

[maintainer]
name = "Daniel Nos"
email = "nos.daniel@pm.me"

[build]
target = "."
flags = "-ldflags=\"-w -s\""
platforms = [ "linux/amd64", "linux/386", "linux/arm", "linux/arm64",
              "windows/amd64", "windows/386", "windows/arm", "windows/arm64",
              "darwin/amd64", "darwin/arm64" ]

[deb]
package = true
architectures = [ "amd64", "386", "arm", "arm64" ]

[rpm]
package = true
build_src = false
architectures = [ "amd64", "386", "arm", "arm64" ]

[pkg]
package = true
architectures = [ "amd64" ]

[appimage]
package = false
architectures = [ ]
